version: '2'

services:
    node:
        build: ./app
    
    bbox:
        image: arqsoft/bbox:202201.1
        ports:
            - "9090:9090" # take in mind this port should assert with the one on the config file
        volumes:
            - ./bbox_config_properties:/opt/bbox/config.properties:ro

    nginx:
        image: nginx:1.21.6
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node

    graphite:
        image: graphiteapp/graphite-statsd:1.1.8-8
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:8.4.6
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.44.0
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

volumes:
    grafana_config:
        driver: local
